export type SecuritySeverity = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

export type SecurityCategory = 
  | 'Authentication'
  | 'Rate Limiting'
  | 'Loans'
  | 'Liquidation'
  | 'Price Feeds'
  | 'Price Monitoring'
  | 'Staking'
  | 'Treasury'
  | 'Protocol'
  | 'Admin'
  | 'External Services'
  | 'Validation'
  | 'WebSocket'
  | 'Background Jobs'
  | 'Database';

export interface SecurityEvent {
  id: string;
  timestamp: Date;
  severity: SecuritySeverity;
  category: SecurityCategory;
  eventType: string;
  message: string;
  details: Record<string, any>;
  source: string;
  alerted: boolean;
  userId?: string;
  ip?: string;
  txSignature?: string;
}

export interface SecurityEventInput {
  severity: SecuritySeverity;
  category: SecurityCategory;
  eventType: string;
  message: string;
  details?: Record<string, any>;
  source: string;
  userId?: string;
  ip?: string;
  txSignature?: string;
}

export interface SecurityStats {
  total: number;
  bySeverity: Record<SecuritySeverity, number>;
  byCategory: Record<string, number>;
  byEventType: Record<string, number>;
  last24Hours: number;
  lastHour: number;
  criticalUnresolved: number;
}

export interface AlertConfig {
  telegram?: { botToken: string; chatId: string; enabled: boolean };
  minSeverity: SecuritySeverity;
  rateLimitMinutes: number;
}

// Pre-defined security event types for consistency
export const SECURITY_EVENT_TYPES = {
  // Authentication
  AUTH_SIGNATURE_EXPIRED: 'AUTH_SIGNATURE_EXPIRED',
  AUTH_SIGNATURE_INVALID: 'AUTH_SIGNATURE_INVALID',
  AUTH_ADMIN_IMPERSONATION: 'AUTH_ADMIN_IMPERSONATION',
  AUTH_MISSING_HEADERS: 'AUTH_MISSING_HEADERS',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_ADMIN_ACCESS: 'AUTH_ADMIN_ACCESS',
  
  // Rate Limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  RATE_LIMIT_SUSPICIOUS: 'RATE_LIMIT_SUSPICIOUS',
  
  // Loans
  LOAN_CREATION_FAILED: 'LOAN_CREATION_FAILED',
  LOAN_REPAY_FAILED: 'LOAN_REPAY_FAILED',
  LOAN_INVALID_COLLATERAL: 'LOAN_INVALID_COLLATERAL',
  LOAN_TREASURY_INSUFFICIENT: 'LOAN_TREASURY_INSUFFICIENT',
  LOAN_PRICE_MANIPULATION: 'LOAN_PRICE_MANIPULATION',
  
  // Liquidation
  LIQUIDATION_TRIGGERED: 'LIQUIDATION_TRIGGERED',
  LIQUIDATION_FAILED: 'LIQUIDATION_FAILED',
  LIQUIDATION_SLIPPAGE_EXCEEDED: 'LIQUIDATION_SLIPPAGE_EXCEEDED',
  LIQUIDATION_RETRY_EXHAUSTED: 'LIQUIDATION_RETRY_EXHAUSTED',
  LIQUIDATION_NO_WALLET: 'LIQUIDATION_NO_WALLET',
  LIQUIDATION_JOB_STARTED: 'LIQUIDATION_JOB_STARTED',
  LIQUIDATION_JOB_COMPLETED: 'LIQUIDATION_JOB_COMPLETED',
  LIQUIDATION_JOB_ERRORS: 'LIQUIDATION_JOB_ERRORS',
  LIQUIDATION_LOANS_FOUND: 'LIQUIDATION_LOANS_FOUND',
  LIQUIDATION_SWAP_STARTED: 'LIQUIDATION_SWAP_STARTED',
  LIQUIDATION_SWAP_SUCCESS: 'LIQUIDATION_SWAP_SUCCESS',
  LIQUIDATION_SWAP_FAILED: 'LIQUIDATION_SWAP_FAILED',
  
  // Price Feeds
  PRICE_API_ERROR: 'PRICE_API_ERROR',
  PRICE_STALE_DATA: 'PRICE_STALE_DATA',
  PRICE_EXTREME_MOVEMENT: 'PRICE_EXTREME_MOVEMENT',
  PRICE_MANIPULATION_DETECTED: 'PRICE_MANIPULATION_DETECTED',
  PRICE_WEBSOCKET_CONNECTED: 'PRICE_WEBSOCKET_CONNECTED',
  PRICE_WEBSOCKET_DISCONNECTED: 'PRICE_WEBSOCKET_DISCONNECTED',
  PRICE_WEBSOCKET_ERROR: 'PRICE_WEBSOCKET_ERROR',
  PRICE_WEBSOCKET_INIT_FAILED: 'PRICE_WEBSOCKET_INIT_FAILED',
  PRICE_WEBSOCKET_FAILED: 'PRICE_WEBSOCKET_FAILED',
  PRICE_WEBSOCKET_RECONNECTING: 'PRICE_WEBSOCKET_RECONNECTING',
  PRICE_INVALID_DATA: 'PRICE_INVALID_DATA',
  PRICE_UPDATE_FAILED: 'PRICE_UPDATE_FAILED',
  PRICE_LIQUIDATION_CHECK_FAILED: 'PRICE_LIQUIDATION_CHECK_FAILED',
  PRICE_API_RATE_LIMITED: 'PRICE_API_RATE_LIMITED',
  PRICE_MONITOR_STOPPED: 'PRICE_MONITOR_STOPPED',
  
  // Staking
  STAKING_CONFIG_ERROR: 'STAKING_CONFIG_ERROR',
  STAKING_INVALID_ADDRESS: 'STAKING_INVALID_ADDRESS',
  STAKING_PDA_MISMATCH: 'STAKING_PDA_MISMATCH',
  STAKING_FETCH_ERROR: 'STAKING_FETCH_ERROR',
  STAKING_CALCULATION_ERROR: 'STAKING_CALCULATION_ERROR',
  STAKING_DISCRIMINATOR_INVALID: 'STAKING_DISCRIMINATOR_INVALID',
  STAKING_POOL_MISMATCH: 'STAKING_POOL_MISMATCH',
  STAKING_OPERATION_FAILED: 'STAKING_OPERATION_FAILED',
  DISTRIBUTION_RATE_LIMITED: 'DISTRIBUTION_RATE_LIMITED',
  DISTRIBUTION_BATCH_FAILED: 'DISTRIBUTION_BATCH_FAILED',
  DISTRIBUTION_EPOCH_LOST: 'DISTRIBUTION_EPOCH_LOST',
  
  // Treasury Security
  TREASURY_LOW_BALANCE: 'TREASURY_LOW_BALANCE',
  TREASURY_CRITICAL_BALANCE: 'TREASURY_CRITICAL_BALANCE',
  TREASURY_LARGE_WITHDRAWAL: 'TREASURY_LARGE_WITHDRAWAL',
  TREASURY_WITHDRAWAL: 'TREASURY_WITHDRAWAL',
  TREASURY_FUNDED: 'TREASURY_FUNDED',
  TREASURY_DRAIN_PATTERN: 'TREASURY_DRAIN_PATTERN',
  
  // Reward Vault Security  
  REWARD_VAULT_LOW_BALANCE: 'REWARD_VAULT_LOW_BALANCE',
  REWARD_VAULT_EMPTY: 'REWARD_VAULT_EMPTY',
  REWARD_VAULT_FUNDED: 'REWARD_VAULT_FUNDED',
  
  // Protocol State
  PROTOCOL_PAUSED: 'PROTOCOL_PAUSED',
  PROTOCOL_RESUMED: 'PROTOCOL_RESUMED',
  PROTOCOL_CONFIG_CHANGED: 'PROTOCOL_CONFIG_CHANGED',
  PROTOCOL_ADMIN_CHANGED: 'PROTOCOL_ADMIN_CHANGED',
  PROTOCOL_FEE_CHANGED: 'PROTOCOL_FEE_CHANGED',
  
  // Large Transactions
  LOAN_LARGE_AMOUNT: 'LOAN_LARGE_AMOUNT',
  LOAN_BURST_ACTIVITY: 'LOAN_BURST_ACTIVITY',
  
  // Admin
  ADMIN_ACCESS: 'ADMIN_ACCESS',
  ADMIN_ACCESS_DENIED: 'ADMIN_ACCESS_DENIED',
  ADMIN_PROTOCOL_PAUSED: 'ADMIN_PROTOCOL_PAUSED',
  ADMIN_PROTOCOL_RESUMED: 'ADMIN_PROTOCOL_RESUMED',
  ADMIN_TREASURY_WITHDRAWAL: 'ADMIN_TREASURY_WITHDRAWAL',
  ADMIN_EMERGENCY_DRAIN: 'ADMIN_EMERGENCY_DRAIN',
  ADMIN_CONFIG_CHANGED: 'ADMIN_CONFIG_CHANGED',
  ADMIN_WHITELIST_MODIFIED: 'ADMIN_WHITELIST_MODIFIED',
  ADMIN_TRANSFER_INITIATED: 'ADMIN_TRANSFER_INITIATED',
  ADMIN_WHITELIST_ADD: 'ADMIN_WHITELIST_ADD',
  ADMIN_WHITELIST_UPDATE: 'ADMIN_WHITELIST_UPDATE',
  ADMIN_WHITELIST_ENABLE: 'ADMIN_WHITELIST_ENABLE',
  ADMIN_WHITELIST_DISABLE: 'ADMIN_WHITELIST_DISABLE',
  ADMIN_WHITELIST_REMOVE: 'ADMIN_WHITELIST_REMOVE',
  ADMIN_WHITELIST_ADDED: 'ADMIN_WHITELIST_ADDED',
  ADMIN_WHITELIST_UPDATED: 'ADMIN_WHITELIST_UPDATED',
  ADMIN_WHITELIST_REMOVED: 'ADMIN_WHITELIST_REMOVED',
  ADMIN_WHITELIST_DISABLED: 'ADMIN_WHITELIST_DISABLED',
  ADMIN_WHITELIST_ENABLED: 'ADMIN_WHITELIST_ENABLED',
  
  // External Services
  JUPITER_API_ERROR: 'JUPITER_API_ERROR',
  JUPITER_SWAP_FAILED: 'JUPITER_SWAP_FAILED',
  PUMPFUN_API_ERROR: 'PUMPFUN_API_ERROR',
  SOLANA_RPC_ERROR: 'SOLANA_RPC_ERROR',
  REDIS_ERROR: 'REDIS_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  
  // Background Jobs
  JOB_FAILED: 'JOB_FAILED',
  JOB_STALLED: 'JOB_STALLED',
  
  // WebSocket
  WS_CONNECTION_FLOOD: 'WS_CONNECTION_FLOOD',
  WS_INVALID_MESSAGE: 'WS_INVALID_MESSAGE',
  WS_UNAUTHORIZED: 'WS_UNAUTHORIZED',
  
  // Error Handling
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNHANDLED_ERROR: 'UNHANDLED_ERROR',
  
  // Validation
  INVALID_PUBKEY: 'INVALID_PUBKEY',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  INVALID_SIGNATURE: 'INVALID_SIGNATURE',
  MALFORMED_REQUEST: 'MALFORMED_REQUEST',
  JOB_QUEUE_OVERFLOW: 'JOB_QUEUE_OVERFLOW',
  
  // Liquidation Loss Tracking
  LIQUIDATION_LOSS_DETECTED: 'LIQUIDATION_LOSS_DETECTED',
  LIQUIDATION_AUTO_BLACKLIST: 'LIQUIDATION_AUTO_BLACKLIST',
  LIQUIDATION_RECOVERY_SUCCESS: 'LIQUIDATION_RECOVERY_SUCCESS',
  
  // Exposure Monitoring
  EXPOSURE_WARNING: 'EXPOSURE_WARNING',
  EXPOSURE_CRITICAL: 'EXPOSURE_CRITICAL',
  EXPOSURE_LIMIT_EXCEEDED: 'EXPOSURE_LIMIT_EXCEEDED',
  
  // Token Auto-Blacklist
  TOKEN_AUTO_BLACKLISTED: 'TOKEN_AUTO_BLACKLISTED',
  TOKEN_BLACKLIST_FAILED: 'TOKEN_BLACKLIST_FAILED',

  // Circuit Breaker
  CIRCUIT_BREAKER_TRIPPED: 'CIRCUIT_BREAKER_TRIPPED',
  CIRCUIT_BREAKER_RESET: 'CIRCUIT_BREAKER_RESET',

  // Daily Summary
  DAILY_SUMMARY: 'DAILY_SUMMARY',
  
  // Rate Limiting
  WALLET_RATE_LIMITED: 'WALLET_RATE_LIMITED',
  WALLET_MAX_LOANS_EXCEEDED: 'WALLET_MAX_LOANS_EXCEEDED',
  
  // Admin Actions
  ADMIN_BLACKLIST_TOKEN: 'ADMIN_BLACKLIST_TOKEN',
  ADMIN_UNBLACKLIST_TOKEN: 'ADMIN_UNBLACKLIST_TOKEN',
  ADMIN_PAUSE_PROTOCOL: 'ADMIN_PAUSE_PROTOCOL',
  ADMIN_RESUME_PROTOCOL: 'ADMIN_RESUME_PROTOCOL',
  
  // Request Validation
  REQUEST_TOO_LARGE: 'REQUEST_TOO_LARGE',
  
  // CSRF Protection
  CSRF_ORIGIN_MISMATCH: 'CSRF_ORIGIN_MISMATCH',
  CSRF_REFERER_MISMATCH: 'CSRF_REFERER_MISMATCH',
  CSRF_TOKEN_MISMATCH: 'CSRF_TOKEN_MISMATCH',
  CSRF_INVALID_REFERER: 'CSRF_INVALID_REFERER',
} as const;